# This theme is based on https://github.com/dirkolbrich/hugo-theme-tailwindcss-starter

name = "GeeksAreForLife"
license = "MIT"
licenselink = "https://github.com/geeksareforlife/geeksareforlife.com-theme/blob/main/LICENSE"
description = "Theme for GeeksAreForLife.com"
homepage = "https://github.com/geeksareforlife/geeksareforlife.com-theme"
tags = ["Hugo", "Tailwind CSS", "theme", "starter", "boilerplate"]
features = []
min_version = "0.69"

[author]
  name = "James Hayward"
  homepage = "https://github.com/geeksareforlife/"
