# This theme is based on https://github.com/dirkolbrich/hugo-theme-tailwindcss-starter

theme = "geeksareforlife.com-theme"
languageCode = "en-us"
baseurl = "http://www.geeksareforlife.com/"
title = "GeeksAreForLife Theme Testing"

# Code higlighting settings
pygmentsCodefences = true
pygmentsStyle = "vs"

[params]
    Author = "James Hayward"
	Copyright = "Copyright © 2020, James Hayward, all rights reserved."
